### PR TITLE
Add automated testing support

### PR DESCRIPTION
**Pull request by gervasiocaj**
Uses [puppeteer](https://github.com/GoogleChrome/puppeteer) and Mocha
Inspired by https://github.com/GoogleChrome/lighthouse/pull/4640/files

### CODE REVIEW

**Comment by nliautaud** [comment]
Wooo, thanks 👍 
I'm not sure if I'll be able to review that correctly as I never did such automated testing.

Could you give me some use case or quick demo ?

PS : there is extensive changes in #34 , it may be great to merge from there.

**Comment by AmineI** [comment]
Quick demo : 

Firstly, install the required node modules, including mocha - a test framework, with `npm install`.

Then use `npm test` to launch the tests that are in test.js.

It basically launch a programmatically controlled chromium instance with your extension loaded, and does each test in there.


It uses mocha; here's a [Getting Started Guide](https://mochajs.org/#getting-started) about it if you're not familiar with it.

[Puppeteer](https://github.com/GoogleChrome/puppeteer#getting-started) is used to control the special Chromium instance.

**Comment by AmineI** [comment]
Two tests are included in tests.js, and it's up to us to create more 

- The first one checks for the correct translation on the movie in  https://trakt.tv/users/gervasiocaj/lists/trakttvstats-tests, by comparing its translated title inside chromium to the (hardcoded) expected one. 

Using a user's list could cause issues honestly though. Plus @gervasiocaj isn't using staging.trakt.tv as suggested in trakt's API docs, 
> to avoid filling production with test data


- The second test opens https://trakt.tv/movies/moana-2016 , translates its title in a few languages and check if the language code shown next to the title is the expected one.

Currently, the tests are failing : I believe it's because he uses pt-br for the test translations, which is not a [ISO 639-1 code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) as required by the extension.

**Comment by AmineI** [comment]
Also, I'd move all these files in a subdirectory - they should not be included with the extension when shipped and should be properly separated.

**Comment by AmineI** [comment]
The 1st test is now passing, however the underlying issue isn't fixed, we'll have to look into it - As you noticed, pt-BR works but not pt-br. However, when submitted by an user in the options windows, the extension always change the entered string to lowercase- we bypassed since we were manually writing to the extension's storage.

I also went ahead and fixed the issue causing the second test to fail in #42.

**Comment by gervasiocaj** [comment]
Will #34 be merged into `master`? If not, why?

**Comment by AmineI** [comment]
> Will #34 be merged into `master`? If not, why?

I believe it'd be merged when deemed stable, so when the individual additions of 0.5 are tested - since @nliautaud marked them as "await testing". He's probably busy ATM though.

image

**Comment by AmineI** [comment]
You'd still have to edit the PR to set the target branch to nliautaud:0.5 so that only the correct diff/commits are shown :)

**Comment by nliautaud** [comment]
Thanks both of you !
Busy indeed :)

**Pull request merged**
